In [1]:

import pandas as pd

data = {
    "Customer_Name": ["Rahul", "Amit", "Priya", "Rahul", "Neha"],
    "Age": [25, 30, None, 25, 28],
    "City": ["Jaipur", "Delhi", "Jaipur", "Jaipur", None],
    "Purchase": [1200, 2500, 1800, 1200, 3000]
}

df = pd.DataFrame(data)

# Display the dataset
df

  Customer_Name   Age    City  Purchase
0         Rahul  25.0  Jaipur      1200
1          Amit  30.0   Delhi      2500
2         Priya   NaN  Jaipur      1800
3         Rahul  25.0  Jaipur      1200
4          Neha  28.0    None      3000

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_Name  5 non-null      object
 1   Age            4 non-null      float64
 2   City           4 non-null      object
 3   Purchase       5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [3]:
print(df.isnull().sum())

Customer_Name    0
Age              1
City             1
Purchase         0
dtype: int64

In [4]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 1

In [5]:
print("Dataset shape:", df.shape)

Dataset shape: (5, 4)

In [6]:
clean_df = df.copy()

In [7]:
clean_df = clean_df.drop_duplicates()

In [8]:
clean_df["Age"] = clean_df["Age"].fillna(
    clean_df["Age"].median()
)

In [9]:
clean_df["City"] = clean_df["City"].fillna("Unknown")

In [10]:
clean_df

  Customer_Name   Age     City  Purchase
0         Rahul  25.0   Jaipur      1200
1          Amit  30.0    Delhi      2500
2         Priya  28.0   Jaipur      1800
4          Neha  28.0  Unknown      3000

In [11]:
print("Original rows:", len(df))
print("Cleaned rows:", len(clean_df))
print("\nRemaining missing values:")
print(clean_df.isnull().sum())

Original rows: 5
Cleaned rows: 4

Remaining missing values:
Customer_Name    0
Age              0
City             0
Purchase         0
dtype: int64

In [12]:
clean_df.to_csv("cleaned_customers.csv", index=False)

In [13]:
clean_df

  Customer_Name   Age     City  Purchase
0         Rahul  25.0   Jaipur      1200
1          Amit  30.0    Delhi      2500
2         Priya  28.0   Jaipur      1800
4          Neha  28.0  Unknown      3000

In [14]:

# Create a before-and-after cleaning report

report = pd.DataFrame({
    "Metric": [
        "Original rows",
        "Cleaned rows",
        "Duplicate rows removed",
        "Missing values before cleaning",
        "Missing values after cleaning"
    ],
    "Value": [
        len(df),
        len(clean_df),
        df.duplicated().sum(),
        df.isnull().sum().sum(),
        clean_df.isnull().sum().sum()
    ]
})

print("DATA CLEANING REPORT")
display(report)

DATA CLEANING REPORT

                           Metric  Value
0                   Original rows      5
1                    Cleaned rows      4
2          Duplicate rows removed      1
3  Missing values before cleaning      2
4   Missing values after cleaning      0

In [15]:

# Save the data cleaning report
report.to_csv("data_cleaning_report.csv", index=False)

print("Report saved successfully!")

# Display the report
display(report)

Report saved successfully!

                           Metric  Value
0                   Original rows      5
1                    Cleaned rows      4
2          Duplicate rows removed      1
3  Missing values before cleaning      2
4   Missing values after cleaning      0

In [16]:

from google.colab import files

files.download("cleaned_customers.csv")
files.download("data_cleaning_report.csv")